services:
  - type: web
    name: calculateur-economies-tabac
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 24.15.0
      - key: VAPID_SUBJECT
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
